sonar.projectKey=neratmatevz_BookmarkUp
sonar.organization=neratmatevz

sonar.sources=src

sonar.cpd.exclusions=src/popup/locales/**

# For the locale files, we need to specify the encoding to avoid issues with special characters.
sonar.sourceEncoding=UTF-8